apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-app-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springcloudapp
  template:
    metadata:
      labels:
        app: springcloudapp
    spec:
      containers:
        - name: spring-cloud-app
          image: tistesoa/springcloudapp:latest
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-app-ser
  namespace: default
spec:
  type: NodePort
  selector:
    app: springcloudapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080